version: '3.8'

services:

  loki: #3100
    image: grafana/loki:2.7.1
    user: "10001"
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log/:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  cadvisor: #8080
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
  
  postgres-exporter: #9187
    image: prometheuscommunity/postgres-exporter
    secrets:
     - default_postgres_pass  
    environment:
      - DATA_SOURCE_URI=host.docker.internal
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS_FILE=/run/secrets/default_postgres_pass
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-exporter: #9121
    image: oliver006/redis_exporter
    #secrets:
    # - default_redis_pass
    #environment:
    # - REDIS_USER=default
    # - REDIS_ADDR=redis://host.docker.internal:6379/
    # - REDIS_PASSWORD_FILE=/run/secrets/default_redis_pass
    command: ["--redis.addr", "redis://default:password@host.docker.internal:6379/"]
    extra_hosts: 
      - "host.docker.internal:host-gateway"

  prometheus: #9090
    image: prom/prometheus:v2.36.2
    user: "472"
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ./storage/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - cadvisor

  node-exporter: #9100
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./storage/grafana_data:/var/lib/grafana
      - ./storage/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config/grafana/config.monitoring

  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./storage/uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
   default_postgres_pass:
      external: true
   default_redis_pass:
      external: true
